#!/usr/bin/env bash
# onboard.sh — (re)onboard the Ireland Network Agents sandbox.
#
# WHAT IT DOES:
#   1. Probe the LLM endpoint with a real POST (not just GET)
#   2. Apply patch-nemoclaw.sh (idempotent pristine restore + patch)
#   3. Run nemoclaw onboard non-interactively with the configured provider
#   3.5. Restore snapshot artifacts (growth state, fault-fatigue, comms, etc.)
#   4. Post-onboard wire-up (cron seed + network server + event engine + gateway bounce)
#   5. Verify end-to-end (baseUrl, domain/, inference, cron, config-hash)
#
# SNAPSHOT RESTORE:
#   By default, if artifacts/snapshots/ exists (created by
#   snapshot-artifacts.sh), the onboard script restores those files into
#   the sandbox after the recreate but before wire-up. This preserves
#   growth progress, fault-fatigue state, agent memory, and cron pacing
#   across re-onboards.
#
#   To skip restore (start completely fresh):
#     ./scripts/onboard.sh --no-restore
#
# CONFIGURATION:
#   The script reads its provider settings from environment variables.
#   Set these before running, or export them in a .env file:
#
#     INFERENCE_URL     OpenAI-compatible endpoint reachable from the sandbox
#                       (e.g. https://api.openai.com/v1)
#     INFERENCE_MODEL   Model identifier (default: openai/gpt-oss-120b)
#     INFERENCE_KEY     API key for the provider (default: dummy)
#     PROBE_MODEL       Smaller model for liveness probes (default: same as INFERENCE_MODEL)
#
#   For a hosted OpenAI-compatible provider:
#     export INFERENCE_URL=https://api.openai.com/v1
#     export INFERENCE_KEY=<your-api-key>
#
# ANTI-PATTERNS — DO NOT:
#   - Patch dist/lib/onboard.js to bypass validate*Selection. If the
#     endpoint probe fails, your LLM endpoint is down — fix it first.
#   - Hand-edit ~/.nemoclaw/source/Dockerfile. It is regenerated by
#     restore_pristine() on every patch-nemoclaw.sh run.
#   - Hand-patch /sandbox/.openclaw/openclaw.json post-onboard. The
#     patch-dockerfile.py config-rewrite bakes the correct baseUrl into
#     the image and recomputes .config-hash so the integrity check passes.
#
# USAGE:
#   ./scripts/onboard.sh
#
# Assumes the invoking user can run docker commands (is in docker group
# or uses sudo). Override with DOCKER_CMD if needed.

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────
INFERENCE_URL="${INFERENCE_URL:?Set INFERENCE_URL to your OpenAI-compatible endpoint}"
INFERENCE_MODEL="${INFERENCE_MODEL:-openai/gpt-oss-120b}"
INFERENCE_KEY="${INFERENCE_KEY:-dummy}"
PROBE_MODEL="${PROBE_MODEL:-$INFERENCE_MODEL}"
POD_NAME="${POD_NAME:-my-assistant}"
NAMESPACE="${NAMESPACE:-openshell}"
CLUSTER="${CLUSTER:-openshell-cluster-nemoclaw}"
DOCKER_CMD="${DOCKER_CMD:-docker}"
SNAPSHOT_DIR="${SNAPSHOT_DIR:-artifacts/snapshots}"
RESTORE_SNAPSHOT=1

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CRON_SEED="$PROJECT_DIR/nemoclaw-blueprint/cron-seed/jobs.json"

# ── CLI flags ────────────────────────────────────────────────────────
for arg in "$@"; do
  case "$arg" in
    --no-restore) RESTORE_SNAPSHOT=0 ;;
    *) warn "unknown flag: $arg" ;;
  esac
done

# ── Helpers ───────────────────────────────────────────────────────────
K_EXEC() {
  $DOCKER_CMD exec "$CLUSTER" kubectl exec -n "$NAMESPACE" "$POD_NAME" -c agent -- "$@"
}
K_CP_IN() {
  local src="$1" dst="$2" base
  base="$(basename "$src")"
  $DOCKER_CMD cp "$src" "$CLUSTER:/tmp/$base"
  $DOCKER_CMD exec "$CLUSTER" kubectl cp "/tmp/$base" "$NAMESPACE/$POD_NAME:$dst" -c agent
}

say() { printf '\n── %s ──\n' "$*"; }
ok()  { printf '  ✓ %s\n' "$*"; }
warn(){ printf '  ⚠ %s\n' "$*"; }
die() { printf '  ✗ %s\n' "$*" >&2; exit 1; }

# ── Step 1: LLM endpoint liveness ────────────────────────────────────
say "Step 1/5: LLM endpoint liveness check"

probe_post() {
  local url="$1" label="$2"
  local body='{"model":"'"$PROBE_MODEL"'","messages":[{"role":"user","content":"ping"}],"max_tokens":3}'
  local attempt code last_err
  for attempt in 1 2 3; do
    last_err=""
    code=$(curl -sS -o /tmp/onboard-probe -w '%{http_code}' --max-time 15 \
           -X POST "$url/chat/completions" \
           -H 'Content-Type: application/json' \
           -H "Authorization: Bearer $INFERENCE_KEY" \
           -d "$body" 2>/tmp/onboard-probe-err || echo "000")
    last_err=$(cat /tmp/onboard-probe-err 2>/dev/null || true)
    if [ "$code" = "200" ] && grep -q 'chat.completion' /tmp/onboard-probe 2>/dev/null; then
      if [ "$attempt" -gt 1 ]; then
        ok "$label → 200 (recovered on attempt $attempt)"
      else
        ok "$label → 200"
      fi
      return 0
    fi
    if [ "$attempt" -lt 3 ]; then
      printf '  … attempt %d failed (code=%s%s), retrying in 3s\n' \
        "$attempt" "$code" "${last_err:+, $last_err}"
      sleep 3
    fi
  done
  printf '  … attempt 3 failed (code=%s%s)\n' "$code" "${last_err:+, $last_err}"
  return 1
}

if probe_post "$INFERENCE_URL" "inference endpoint"; then
  :
else
  die "LLM endpoint not responding at $INFERENCE_URL. Fix your provider before onboarding."
fi

# ── Step 2: Apply patches (idempotent pristine restore) ──────────────
say "Step 2/5: patch-nemoclaw.sh (OPS_CONFIG_URL=$INFERENCE_URL)"

OPS_CONFIG_URL="$INFERENCE_URL" \
  "$PROJECT_DIR/nemoclaw-blueprint/patch-nemoclaw.sh"
ok "patches applied"

grep -q "COPY nemoclaw-blueprint/project-files/domain" \
  "$PROJECT_DIR/nemoclaw-blueprint/patch-dockerfile.py" \
  || die "patch-dockerfile.py is missing the domain/ COPY line"
ok "patch-dockerfile.py sanity: domain/ COPY present"

# ── Step 3: nemoclaw onboard (non-interactive) ───────────────────────
say "Step 3/5: nemoclaw onboard --recreate-sandbox"

LOG=/tmp/onboard-$(date +%s).log
NEMOCLAW_ACCEPT_THIRD_PARTY_SOFTWARE=1 \
NEMOCLAW_PROVIDER=custom \
NEMOCLAW_ENDPOINT_URL="$INFERENCE_URL" \
NEMOCLAW_MODEL="$INFERENCE_MODEL" \
COMPATIBLE_API_KEY="$INFERENCE_KEY" \
NEMOCLAW_RECREATE_SANDBOX=1 \
nemoclaw onboard \
  --non-interactive \
  --recreate-sandbox \
  --yes-i-accept-third-party-software \
  > "$LOG" 2>&1 &
OB_PID=$!

while kill -0 "$OB_PID" 2>/dev/null; do
  sleep 3
  tail -n 1 "$LOG" 2>/dev/null | sed 's/^/  | /'
done
wait "$OB_PID" || die "nemoclaw onboard failed — see $LOG"
ok "onboard exited 0 (full log: $LOG)"

# ── Step 3.5: Restore snapshot artifacts ────────────────────────────
SNAPSHOT_ABS=""
if [ "$RESTORE_SNAPSHOT" -eq 1 ]; then
  # Resolve snapshot dir (may be relative to project)
  if [ -d "$SNAPSHOT_DIR" ]; then
    SNAPSHOT_ABS="$(cd "$SNAPSHOT_DIR" && pwd)"
  fi
fi

if [ -n "$SNAPSHOT_ABS" ]; then
  say "Step 3.5/5: Restoring snapshot from $SNAPSHOT_ABS"
  RESTORED=0 SKIPPED=0

  # Restore workspace artifacts (flat files from snapshot root)
  WS_ARTIFACTS=/sandbox/.openclaw-data/workspace/artifacts
  for f in "$SNAPSHOT_ABS"/*; do
    [ -f "$f" ] || continue
    name="$(basename "$f")"
    case "$name" in
      # Skip non-artifact files that snapshot stores alongside
      jobs.json) ;;          # handled separately for cron
      *)
        K_CP_IN "$f" "$WS_ARTIFACTS/$name"
        RESTORED=$((RESTORED + 1))
        ;;
    esac
  done

  # Restore MEMORY.md (snapshot stores it at root, workspace expects it at workspace level)
  if [ -f "$SNAPSHOT_ABS/MEMORY.md" ]; then
    K_CP_IN "$SNAPSHOT_ABS/MEMORY.md" /sandbox/.openclaw-data/workspace/MEMORY.md
    RESTORED=$((RESTORED + 1))
  fi

  # Ensure sub-directories exist inside the fresh pod
  K_EXEC mkdir -p /sandbox/.openclaw-data/workspace/artifacts/atlas-history /sandbox/.openclaw-data/workspace/network/ireland

  # Restore atlas-history directory
  if [ -d "$SNAPSHOT_ABS/atlas-history" ]; then
    for f in "$SNAPSHOT_ABS/atlas-history"/*; do
      [ -f "$f" ] || continue
      K_CP_IN "$f" "/sandbox/.openclaw-data/workspace/artifacts/atlas-history/$(basename "$f")"
      RESTORED=$((RESTORED + 1))
    done
  fi

  # Restore network state (network/ireland/state.json)
  if [ -f "$SNAPSHOT_ABS/network/state.json" ]; then
    K_CP_IN "$SNAPSHOT_ABS/network/state.json" /sandbox/.openclaw-data/workspace/network/ireland/state.json
    RESTORED=$((RESTORED + 1))
  fi

  # Restore cron state — prefer snapshot (preserves agent-set pacing)
  if [ -f "$SNAPSHOT_ABS/jobs.json" ]; then
    K_CP_IN "$SNAPSHOT_ABS/jobs.json" /sandbox/.openclaw-data/cron/jobs.json
    ok "cron jobs.json restored from snapshot (preserves agent pacing)"
    RESTORED=$((RESTORED + 1))
  fi

  ok "$RESTORED artifact(s) restored from snapshot"
else
  if [ "$RESTORE_SNAPSHOT" -eq 1 ]; then
    say "Step 3.5/5: No snapshot found at $SNAPSHOT_DIR — starting fresh"
  fi
fi

# ── Step 4: Post-onboard wire-up ─────────────────────────────────────
say "Step 4/5: Post-onboard wiring (network server + event engine + gateway)"

# Seed cron from baseline only if snapshot didn't already restore it
if [ -z "$SNAPSHOT_ABS" ] || [ ! -f "$SNAPSHOT_ABS/jobs.json" ]; then
  [ -f "$CRON_SEED" ] || die "cron seed file missing: $CRON_SEED"
  K_CP_IN "$CRON_SEED" /sandbox/.openclaw-data/cron/jobs.json
  ok "cron jobs.json seeded from baseline"
fi

cat > /tmp/onboard-wireup.sh <<'WIREUP'
#!/bin/sh
set -e

# 1. Network server
if pgrep -f "node server.js" >/dev/null 2>&1; then
  echo "network server already running"
else
  cd /sandbox/network && nohup node server.js > /tmp/network-server.log 2>&1 &
  echo "network server started (pid $!)"
fi

# 1b. Event engine
if pgrep -f "event-engine.js" >/dev/null 2>&1; then
  echo "event engine already running"
else
  if [ -f /sandbox/network/ireland/event-engine.js ]; then
    cd /sandbox/network && nohup node ireland/event-engine.js > /tmp/event-engine.log 2>&1 &
    echo "event engine started (pid $!)"
  fi
fi

# 2. Seed workspace artifacts if absent (skipped if snapshot restore already placed them)
mkdir -p /sandbox/.openclaw-data/workspace/artifacts
touch /sandbox/.openclaw-data/workspace/artifacts/agent-comms.jsonl
if [ -f /sandbox/.openclaw-data/workspace/artifacts/state.json ]; then
  echo "state.json: restored from snapshot, keeping"
else
  echo '{"growth_target":8000,"growth_wave_count":0}' \
    > /sandbox/.openclaw-data/workspace/artifacts/state.json
fi
if [ -f /sandbox/.openclaw-data/workspace/artifacts/signals.json ]; then
  echo "signals.json: restored from snapshot, keeping"
else
  echo '[]' > /sandbox/.openclaw-data/workspace/artifacts/signals.json
fi
if [ -f /sandbox/.openclaw-data/workspace/artifacts/rebuild-status.json ]; then
  echo "rebuild-status.json: restored from snapshot, keeping"
else
  echo '{"status":"ok","cells":266,"hash":"seed"}' \
    > /sandbox/.openclaw-data/workspace/artifacts/rebuild-status.json
fi

# 3. Copy playbooks into workspace
[ -d /sandbox/playbooks ] && \
  cp /sandbox/playbooks/*.md /sandbox/.openclaw-data/workspace/ 2>/dev/null || true

# 4. Symlinks for the agent's working dir
rm -rf /sandbox/artifacts 2>/dev/null || true
ln -sf /sandbox/.openclaw-data/workspace/artifacts /sandbox/artifacts
ln -sf /sandbox/agents /sandbox/.openclaw-data/workspace/agents 2>/dev/null || true
ln -sf /sandbox/network /sandbox/.openclaw-data/workspace/network 2>/dev/null || true
ln -sf /sandbox/domain /sandbox/.openclaw-data/workspace/domain 2>/dev/null || true

# 5. Bounce the gateway so it loads the fresh jobs.json
for p in /proc/[0-9]*; do
  comm=$(cat "$p/comm" 2>/dev/null || echo "")
  case "$comm" in openclaw-gate*)
    kill "$(basename "$p")" 2>/dev/null || true
    ;;
  esac
done
_i=0
while pgrep -f openclaw-gate >/dev/null 2>&1 && [ $_i -lt 20 ]; do
  _i=$((_i+1))
  sleep 0.1
done
cd /sandbox
HOME=/sandbox nohup openclaw gateway run > /tmp/gateway.log 2>&1 &
echo "gateway restarted (pid $!)"
echo wireup done
WIREUP

K_CP_IN /tmp/onboard-wireup.sh /tmp/wireup.sh
K_EXEC sh /tmp/wireup.sh
ok "in-pod wire-up complete"

sleep 3

# ── Step 5: Verify ───────────────────────────────────────────────────
say "Step 5/5: Verification"

# Config hash matches openclaw.json
HASH_LIVE=$(K_EXEC sh -c 'sha256sum /sandbox/.openclaw/openclaw.json 2>/dev/null | cut -d" " -f1')
HASH_PINNED=$(K_EXEC sh -c 'cut -d" " -f1 /sandbox/.openclaw/.config-hash')
[ "$HASH_LIVE" = "$HASH_PINNED" ] && ok "config-hash integrity check passes" \
  || die "config-hash mismatch: live=$HASH_LIVE pinned=$HASH_PINNED"

# /sandbox/domain present
K_EXEC ls /sandbox/domain/index.js >/dev/null 2>&1 && ok "/sandbox/domain/ baked in" \
  || die "/sandbox/domain/ missing from image"

# Network server listening on 8090
K_EXEC sh -c 'ss -tln | grep -q :8090' >/dev/null 2>&1 && ok "network server on :8090" \
  || warn "network server not listening on :8090 — check /tmp/network-server.log inside pod"

# Inference POST from inside the sandbox
probe_sandbox_inference() {
  local attempt code body='{"model":"'"$PROBE_MODEL"'","messages":[{"role":"user","content":"ping"}],"max_tokens":3}'
  for attempt in 1 2 3; do
    code=$(K_EXEC sh -c "curl -sS -o /dev/null -w '%{http_code}' --max-time 25 -X POST \
      \$(grep -o '\"baseUrl\":\"[^\"]*\"' /sandbox/.openclaw/openclaw.json | head -1 | cut -d'\"' -f4)/chat/completions \
      -H 'Content-Type: application/json' \
      -d '$body'" 2>/dev/null || echo "000")
    if echo "$code" | grep -q 200; then
      if [ "$attempt" -gt 1 ]; then
        ok "end-to-end inference from sandbox: 200 (recovered on attempt $attempt)"
      else
        ok "end-to-end inference from sandbox: 200"
      fi
      return 0
    fi
    if [ "$attempt" -lt 3 ]; then
      printf '  … sandbox inference attempt %d failed (code=%s), retrying in 3s\n' "$attempt" "$code"
      sleep 3
    fi
  done
  warn "end-to-end inference POST from sandbox did not return 200 after 3 attempts"
  warn "  (first cron tick should confirm real inference)"
}
probe_sandbox_inference

# Cron jobs registered
CRON_COUNT=$(K_EXEC sh -c 'HOME=/sandbox openclaw cron list 2>/dev/null | grep -cE "sentinel|oracle|architect"')
[ "$CRON_COUNT" = "3" ] && ok "all 3 cron jobs registered" \
  || warn "expected 3 cron jobs, got $CRON_COUNT"

say "Onboard complete."
echo "  Full onboard log: $LOG"
echo "  First sentinel tick in <= 5 min; watch with:"
echo "    $DOCKER_CMD exec $CLUSTER kubectl exec -n $NAMESPACE $POD_NAME -c agent -- tail -f /sandbox/artifacts/agent-comms.jsonl"
